name: API Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test:cards
        
      - name: Code Coverage
        run: npm run coverage

      - name: Check for vulnerabilities
        run: npm audit --audit-level=high
